### ISSUE TITLE
提问：关于cdn引入element-ui问题

### ISSUE THREAD

**Issue by JamesDream87** [d2-projects/d2-admin-start-kit#13]
你好，请问一下关于cdn引入element-ui后报错如何解决？
Unknown custom element。
![Uploading 微信截图_20190218184005.png…]()

**Comment by JamesDream87** [comment]
![Uploading 微信截图_20190218184005.png…]()
![Uploading 微信截图_20190218184005.png…]()

**Comment by JamesDream87** [comment]
[](https://ibb.co/q11JNQv)

**Comment by JamesDream87** [comment]
[https://ibb.co/q11JNQv](图片链接)

**Comment by FairyEver** [comment]
https://segmentfault.com/q/1010000009568751 参考这里的一些方案
