### ISSUE TITLE
本项目下安装v-charts的ve-map组件不渲染，空项目正常

### ISSUE THREAD

**Issue by Rackar** [d2-projects/d2-admin-start-kit#15]
今日新clone的本项目 
安装echarts v-charts之后 其他图表渲染都正常
<ve-map :data="chartData"></ve-map> 地图只占位不渲染，无报错信息打印

我在一个空项目里测了v-charts没问题 写法也没问题
又下载了完整版的d2-admin，里面的ve-map表现正常，
怀疑是否组件版本问题，于是参考完整版内的版本：
降级了echarts 由4.2.1  到  4.1.0
降级v-charts由1.19.0 到 1.17.6
问题依旧

**Comment by zhuzhh** [comment]
debugger跟着代码走一遍，看看哪一步出问题了

**Comment by FairyEver** [comment]
mockjs影响地图的加载，你可以测试一下

**Comment by Rackar** [comment]
> mockjs影响地图的加载，你可以测试一下

确实是 关掉后正常 非常感谢
