### ISSUE TITLE
点击菜单，控制台报错警告

### ISSUE THREAD

**Issue by duke-git** [d2-projects/d2-admin-start-kit#22]
```
为了统一格式，请将下面一行复制到 `Title` 栏，然后删除这部分
👾 BUG | 你的标题
```
vue-router.esm.js:2007 Uncaught (in promise) NavigationDuplicated {_name: "NavigationDuplicated", name: "NavigationDuplicated"}
![image](https://user-images.githubusercontent.com/5037603/64154131-c47aa680-ce62-11e9-9d04-12d9f2f5d963.png)

如果需要，在这里描述具体内容

**Comment by FairyEver** [comment]
https://github.com/d2-projects/d2-admin/blob/e8a231fb60198aa23af01f91320751ea82dfdd69/src/router/index.js#L14-L22
