### ISSUE TITLE
🤔 提问 | 为何登录sys.login.js 无法执行异步调用 进行认证用户？

### ISSUE THREAD

**Issue by anzaimary** [d2-projects/d2-admin-start-kit#26]
小弟不才 看了下登录相关代码 主要认证在 src->mock->api->sys.login.js 实现。认证逻辑主要是在静态数组 userDB中查找是否 用户名密码匹配 请问大佬 可不可以在这个js中适用 异步请求进行认证操作 谢谢了 小弟研究两天了 还是没研究出来可不可以用 异步请求

**Comment by anzaimary** [comment]
附上代码块
`const userDB = [
  { username: 'admin', password: 'admin', uuid: 'admin-uuid', name: 'Admin' },
  { username: 'editor', password: 'editor', uuid: 'editor-uuid', name: 'Editor' },
  { username: 'user1', password: 'user1', uuid: 'user1-uuid', name: 'User1' }
]

export default [
  {
    path: '/api/login',
    method: 'post',
    handle ({ body }) {
      const user = userDB.find(e => e.username === body.username && e.password === body.password)
      if (user) {
        return {
          code: 0,
          msg: '登录成功',
          data: {
            ...user,
            token: '8dfhassad0asdjwoeiruty'
          }
        }
      } else {
        return {
          code: 401,
          msg: '用户名或密码错误',
          data: {}
        }
      }
    }
  }
]`

**Comment by FairyEver** [comment]
你的思路错了，既然你有真正的接口，为什么还需要 mock 呢？去掉项目里所有关于 mock 的东西，在 api 文件夹里写你自己的实际接口，页面中通过访问上一步你写好的接口方法获取数据即可

**Comment by FairyEver** [comment]
你附注的那些代码都是应该删除的
