### ISSUE TITLE
变成template之后commit的hash值全变掉了，原来fork的内容无法从这个给源更新了嘛？

### ISSUE THREAD

**Issue by xxbld** [d2-projects/d2-admin-start-kit#31]
![image](https://user-images.githubusercontent.com/13309211/74296596-414d6d00-4d7f-11ea-941f-8f2782fef2cb.png)

**Comment by Aysnine** [comment]
最好重新fork

因为使用了bfg去清理仓库历史中无用的大文件，来减小仓库体积，导致了commit hash受影响

好处是仓库的体积现在更小了，以前有上百兆，现在只有二三十兆
