### ISSUE TITLE
🖐 其它问题 | 新手上路遇到的问题和心路历程

### ISSUE THREAD

**Issue by oopsRookie** [d2-projects/d2-admin-start-kit#37]
初学者感到有些繁琐
**背景：** 未接触过vue等相关框架，用过Jquery等，又一定的前端开发基础
**经历：** 4天认真仔细地看完了整个开发文档+elmentUI大部分文档API

**问题：** 我的项目仅需一个上传简单数据的平台，而项目封装过于严格和庞大。虽然这几天攻克了一个又一个问题（头疼），最终还是卡在了axios跨域post请求上（postman可以跑通）。最终决定放弃使用该框架。
**项目优点：** 显然，集成了很多模板，本身也模板化管理。适用于商业级项目，利于后期工程管理。
**项目缺点：** 模块化也是问题所在，尤其是对小白来说，大量新模块的引入+严格工程模块化直接摸不着头脑。/头疼 `本身该分支是start-kit，个人认为应该再降低些门槛，减少使用者相关面上的知识水平。`

**建议：** 减弱框架对复杂模块的集成和封装，降低需要修改的配置，只保留核心即可。更适用于`小型项目上手`以及初学者入门该体系。文档还可以再详细些，尤其是封装过的模块。

**当然，作者很辛苦，也非常感谢作者的付出。绝无贬低作者辛勤付出之意。**
`以上仅为作为完全小白的我，这几天的使用心得和小建议，使用过程很曲折，痛苦。`

**Comment by FairyEver** [comment]
其实最后卡住你的问题 "最终还是卡在了axios跨域post请求上（postman可以跑通）"，这个问题和这个项目其实并没有关系，接口服务没有做跨域处理可以让后端做跨域或者前端启动开发环境的代理，你可以找一些关于 “CORS” 和 “简单请求和复杂请求” 相关的资料看一看。

注：postman 不会发生跨域的

也祝你工作顺利
