### ISSUE TITLE
🤔 提问 | Proxy error: Could not proxy request /api/site/login from localhost:8080

### ISSUE THREAD

**Issue by crstudio** [d2-projects/d2-admin-start-kit#49]
我在 `vue.config.js` 里的 `devServer` 下面添加 `proxy` 配置，按照你的文档里的跨域：
```
proxy: {
      '/api': {
        target: 'http://admin.localhost',
        ws: true,
        changeOrigin: true,
      },
    }
```
`sys.user.api.js` 也改成 `request` 了，
但是接口提示：Proxy error: Could not proxy request /api/site/login from localhost:8080 to http://admin.localhost (ENOTFOUND)
这个问题怎么解决？

**Comment by crstudio** [comment]
重启电脑后自己好了，难道nginx的serve有DNS缓存？

**Comment by crstudio** [comment]
今天重启电脑又不行了，又报错了，奇怪！

**Comment by Aysnine** [comment]
能提供下更详细的报错信息吗

**Comment by crstudio** [comment]
我自己的问题，因为chrome和firefox自动会对.localhost后缀的域名解析到127.0.0.1，所以自然没有在host文件里里写入这个admin.localhost域名到127.0.0.1，所以node不识别，但是曾经有一次能代理了，这就很奇怪了。总之我现在在host文件里加入了，就正常了。
