### ISSUE TITLE
能否支持布局可控

### ISSUE THREAD

**Issue by mcmf** [d2-projects/d2-admin-start-kit#5]
如果业务简单 可能不需要顶部菜单 只需要左侧菜单就能实现业务。
![image](https://user-images.githubusercontent.com/19700237/44941454-6a1eb400-add0-11e8-90eb-5b9f9490ca3f.png)

如果业务复杂 需要顶部菜单点击后列出左侧菜单
![image](https://user-images.githubusercontent.com/19700237/44941466-8e7a9080-add0-11e8-8f65-a3d9e44c6738.png)

能否全局有个可控切换

**Comment by FairyEver** [comment]
你可以手动修改 layout 文件，删除侧边栏相关的代码
