### ISSUE TITLE
生产环境如何不出现debugger

### ISSUE THREAD

**Issue by infiniteDemon** [d2-projects/d2-admin-start-kit#51]
```
为了统一格式，请将下面一行复制到 `Title` 栏，然后删除这部分
🤔 提问 | 生产环境如何不出现debugger
```

就是打包上传了之后 在实际环境中使用的时候 点击某个按钮 
如果出现请求错误就会自动Debugger,用户体验好差啊。。

**Comment by Aysnine** [comment]
eslint 是有检查的：
https://github.com/d2-projects/d2-admin-start-kit/blob/38338b5025a1b1072045f181862f8f794f33a9ab/.eslintrc.js#L12

打包生产环境时应该有错误提示。除非你是打包有问题。

**Comment by infiniteDemon** [comment]
`# 构建预览页面

# 指定构建模式
NODE_ENV=production

# 标记当前构建方式
VUE_APP_BUILD_MODE=PREVIEW

# 显示源码按钮
VUE_APP_SCOURCE_LINK=TRUE

# 部署路径
VUE_APP_PUBLIC_PATH=/
`
`# 开发环境

# 页面 title 前缀
VUE_APP_TITLE=D2Admin Dev
`
`# 所有环境默认

# 页面 title 前缀
VUE_APP_TITLE=D2Admin

# 网络请求公用地址
VUE_APP_API=http://127.0.0.1:1111/

# 仓库地址
VUE_APP_REPO=https://github.com/d2-projects/d2-admin-start-kit

# 国际化配置
VUE_APP_I18N_LOCALE=zh-chs
VUE_APP_I18N_FALLBACK_LOCALE=en

# element 颜色
VUE_APP_ELEMENT_COLOR=#409EFF
`
这是我的打包配置 
eslint的配置 应该也没有修改过
`
module.exports = {
  root: true,
  env: {
    node: true
  },
  'extends': [
    'plugin:vue/essential',
    '@vue/standard'
  ],
  rules: {
    'no-console': process.env.NODE_ENV === 'production' ? 'error' : 'off',
    'no-debugger': process.env.NODE_ENV === 'production' ? 'error' : 'off'
  },
  parserOptions: {
    parser: 'babel-eslint'
  },
  overrides: [
    {
      files: [
        '**/__tests__/*.{j,t}s?(x)',
        '**/tests/unit/**/*.spec.{j,t}s?(x)'
      ],
      env: {
        jest: true
      }
    }
  ]
}
`
但是依旧出现了这个问题 是我部署时的环境问题吗

**Comment by infiniteDemon** [comment]
不好意思，之前有些忙 我指的是我打包之后 上传到生产环境中 在网络中使用的时候 双击tabs或者请求失败，会自动debugger. 代码中并不任何debugger的代码. 算了，我再看看吧，有可能是我浏览器vue-dev-tool造成的，但是我使用vue2.6版本的项目并不会出现这样的问题. 我是名后端同学，对vue这块了解，还是希望停留在即开即用快速开发上，暂时没有精力去深入研究探索vue新版的各种特性.谢谢大佬解答回复。
