### ISSUE TITLE
🖐 其它问题 |  npm run build 后部署内网的服务器瞬间傻逼

### ISSUE THREAD

**Issue by j421037** [d2-projects/d2-admin-start-kit#63]
仔细一看全部都在index.html 引入了cdn  操蛋

**Comment by j421037** [comment]
内网服务器与外网隔离

**Comment by Aysnine** [comment]
把这个配置 CDN 的数组清空即可：
https://github.com/d2-projects/d2-admin-start-kit/blob/master/dependencies-cdn.js

``` js
module.exports = [
 // ...
]
```

**Comment by j421037** [comment]
解决了。。 我把index.html 的for 循环注释掉了，最近比较忙。忘记回复了  见谅
